// STAFF SHEET
const STAFF_SHEET_ID = 1162211165;
const STAFF_ROLE_COLUMN_HEADER = 'role';

// UNITS SHEET
const UNITS_SHEET_ID = 1436796628;
const UNITS_UNIT_TYPE_COLUMN_HEADER = 'unit type';
const UNITS_UNIT_COUNT_COLUMN_HEADER = 'unit count';
const UNITS_MISSING_UNITS_COLUMN_HEADER = 'missing unit count';

// TIMELINE SHEET
const MAIN_TIMELINE_SHEET_ID = 224444304;
const CONSTRUCTION_TIMELINE_SHEET_ID = 1618658099;
const INFRASTRUCTURE_TIMELINE_SHEET_ID = 374017605;

// TIMELINE COLUMNS HEADERS
const TIMELINE_PARAM_NAME_COLUMN_NUMBER = 2;
const TIMELINE_CATEGORY_COLUMN_HEADER = 'category';

const TIMELINE_HEADER_ROW_NUM = 3;
const TIMELINE_FIRST_QUARTER_COL = 3;

// TIMELINE CATEGORIES
const TIMELINE_CONST_PLAN_CATEGORY = 'Construction Plan';
const TIMELINE_CONST_PLAN_PARAM_POSTFIX = ' construction count';

const TIMELINE_CONST_COSTS_CATEGORY = 'Construction Costs';
const TIMELINE_CONST_COST_PARAM_POSTFIX = ' construction cost';

const TIMELINE_STAFF_CATEGORY = 'Staff';
const TIMELINE_STAFF_PARAM_POSTFIX = 's headcount';

const TIMELINE_MONTHLY_NET_SALARIES_CATEGORY = 'Monthly Net Salaries';
const TIMELINE_MONTHLY_NET_SALARIES_PARAM_POSTFIX = 's monthly net salaries';

const TIMELINE_NET_SALARIES_CATEGORY = 'Net Salaries';
const TIMELINE_NET_SALARIES_PARAM_POSTFIX = 's net salaries';

const TIMELINE_INFRASTRUCTURE_COSTS_CATEGORY = 'Infrastructure Costs';
const TIMELINE_INFRASTRUCTURE_COSTS_PARAM_POSTFIX = '';
